(function(g){var window=this;'use strict';var V1=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},W1=function(a){return g.ZC(a)&&a.S("web_player_i_see_captions_3")},sVa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.j)return c=a+"|"+b,g.A(f,g.wt(),2);if(3!=f.j){d=f.u;if(!d)throw g.Vs("gct");return g.A(f,g.CD(d),3)}e=f.u;return f.return(e.get("captions",c))})},tVa=function(a,b){var c=new g.FD;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},uVa=function(a,b,c){sVa(a,b).then(function(d){d&&c(d.trackData,new g.FD(d.metadata))})},X1=function(){this.segments=[]},vVa=function(a,b){var c=g.qc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.gc(a.segments,c),g.gc(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.nc(a.segments,c,0,b),g.nc(a.segments,c+1,0,b)))},Y1=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.Z=c;this.N=d;this.D=e;this.X=f;this.Y=this.player.V();this.C=new X1;this.J=-1;this.B=this.u=this.j=null;this.K=new g.L(this.xN,1E3,this);this.events=new g.cA(this);g.H(this,this.K);g.H(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.qB);this.qB();this.xN()},wVa=function(a){return a.j&&a.j.C?a.j.C+a.player.rd()<a.player.getCurrentTime():!1},xVa=function(a,b){var c=g.cz(g.yz(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.Mr(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,k=g.jta(e);if(k){e=g.yz(a.u,a.policy,{});a.u.Lj(e,k);xVa(a,a.u);break a}f?a.player.Aa("capfail",{status:e.status}):(k=a.u.j[0].Na,null!=a.N&&a.J!==k&&(f=a.u.j[0],a.D?a.N(e.response,1E3*(f.startTime+a.player.rd())):a.N(e.responseText,1E3*(f.startTime+a.player.rd())),a.J=k))}a.u=null;a.B=null}}).Ch(function(e){a.u=null;
a.B=null;var f;a.player.Aa("capfail",{status:null==(f=e.xhr)?void 0:f.status});a.Qa()});
a.u=b;vVa(a.C,a.u.j[0].Na)},Z1=function(a,b){g.yL.call(this,b.V());
this.j=a;this.I=b;this.B=null;this.D=!1;this.J=g.aD(this.I.V())&&!this.j.isManifestless},zVa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.AL(e,b||null)){var f=e.info.id,k=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.ITa.get(e);null==n&&(n=yVa[e]||yVa[e.replace(/-/g,"_")],g.ITa.set(e,n));k=n||k}c.push(new g.FD({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},AVa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},BVa=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.AL(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},$1=function(a){if(!CVa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(DVa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},a2=function(a,b,c,d,e,f,k,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Ed);a.params.Ed&&Object.assign(n,a.params.Ed);Object.assign(n,c.Ed);m.Ed=n;g.W.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===m.Xf?"rtl":"ltr",tabindex:"0",lang:m.lang},U:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.xa=!1;this.u=a;this.Ea=this.ya=null;this.playerWidth=f;this.playerHeight=k;this.J=null;this.maxWidth=.96*f;this.Sa=.96*
k;this.j=m;this.rb=c;this.Ia=b;this.C=this.Da("captions-text");this.jb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Z=e/360*16;!l.ob("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.Z=d/640*16);this.type=0;this.Wa=this.Z*EVa(n);a=new g.ov(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.uS,this);a.subscribe("dragmove",this.tS,this);a.subscribe("dragend",this.sS,this);this.Ya=this.Xa=0;b=
"";this.j.windowOpacity&&(a=$1(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":FVa[this.j.textAlign]};this.jb&&(a["border-radius"]=b?this.Wa/8+"px":"");if(this.B=2===this.u.params.Xf||3===this.u.params.Xf)b=this.element,c="vertical-rl",1===this.j.lI&&(c="vertical-lr"),g.Nc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Nm(b,"-o-writing-mode",c),g.Nm(b,"-webkit-writing-mode",c),g.Nm(b,"writing-mode",
c),g.Nm(b,"text-orientation","upright"),g.M(b,"ytp-vertical-caption"),3===this.u.params.Xf&&(g.Nm(b,"text-orientation",""),g.Nm(b,"transform","rotate(180deg)"));g.Nm(this.element,a);switch(this.j.Ci){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},EVa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},GVa=function(a,b){var c={},d=b.background?b.background:a.j.Ed.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Ed.backgroundOpacity;d=$1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.jb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*EVa(b)+"px";d=1;e=b.color||a.j.Ed.color;if(b.color||null!=b.textOpacity)e=$1(e),d=null==b.textOpacity?a.j.Ed.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.tE&&(k=e=b.tE);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.cs()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Ed.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Oj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.jV&&(c.visibility="hidden");1===b.MM&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.eD||g.Ts,3===a.u.params.Xf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.gk||2===b.gk||3===b.gk||4===b.gk||5===b.gk)if(g.eD)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.gk){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},HVa=function(a){a.J=g.ci("SPAN");
g.Nm(a.J,{display:"block"});g.M(a.J,"caption-visual-line");a.C.appendChild(a.J)},IVa=function(a,b){var c=g.ci("SPAN");
g.Nm(c,{display:"inline-block","white-space":"pre-wrap"});g.Nm(c,GVa(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Nm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Nm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},JVa=function(a,b,c){a.xa=a.xa||!!c;
var d={};Object.assign(d,a.j.Ed);Object.assign(d,c||b.j);Object.assign(d,a.rb.Ed);(c=!a.J)&&HVa(a);for(var e=a.ya&&a.Ea&&g.fg(d,a.Ea)?a.ya:IVa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(HVa(a),e=IVa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.di(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.eD||!g.Pm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Pm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Hf?g.Nm(e,m,"1em"):g.Nm(e,m,"0.5em")))}a.Ea=d;a.ya=e;a.D.push(b)},b2=function(a,b,c,d){g.yL.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.C=b.JF},c2=function(a,b,c,d,e,f,k,l){a2.call(this,a,b,c,d,e,f,k,l);
this.type=1},d2=function(a,b,c,d,e,f,k,l){a2.call(this,a,b,c,d,e,f,k,l);
this.type=2;this.K=[];this.X=this.N=this.Ja=0;this.ma=NaN;this.ib=0;this.qb=null;this.Ra=new g.L(this.kY,433,this);g.M(this.element,"ytp-caption-window-rollup");g.H(this,this.Ra);g.Nm(this.element,"overflow","hidden")},KVa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.lI&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},LVa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Wm,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.N=d;b=Math;c=b.max;isNaN(a.ma)&&((d=a.j.Kn)?(e=g.ci("SPAN"),g.ji(e,"\u2013".repeat(d)),g.Nm(e,GVa(a,a.j.Ed)),a.C.appendChild(e),a.ma=e.offsetWidth,a.C.removeChild(e)):a.ma=0);d=a.C;a.X=c.call(b,a.ma,a.ib,(a.B?d.offsetHeight:d.offsetWidth)+1)},MVa=function(a,b){LVa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.Ja){var d=0<c&&0===a.Ja;b||isNaN(c)||d||(g.M(a.element,"ytp-rollup-mode"),g.xp(a.Ra));g.Nm(a.C,"transform",KVa(a,c));a.Ja=c}LVa(a)},e2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.Fw.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=k},f2=function(a,b,c,d,e){g.Fw.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},NVa=function(a){var b="_"+g2++;
return new f2(0,0x8000000000000,0,b,a)},PVa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Ce){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=OVa(l.textContent,n.textContent,p.textContent,f.textContent,k);return new e2(a,b,e,c,l,d,m)}switch(m.Ce){case 9:case 10:m.gk=1;break;case 11:m.gk=2;break;case 12:m.gk=3;break;case 13:m.gk=4;break;case 14:m.gk=5}return new e2(a,b,e,c,l.textContent||"",d,m)},OVa=function(a,b,c,d,e){var f=g.cs(),k=
f?g.ci("DIV"):g.ci("RUBY"),l=g.ci("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.ci("DIV"):g.ci("RP");a.textContent=b;k.appendChild(a);b=f?g.ci("DIV"):g.ci("RT");b.textContent=c;k.appendChild(b);c=e.Ce;if(10===c||11===c||12===c||13===c||14===c)if(g.Nm(b,"text-emphasis-style","filled circle"),g.Nm(b,"text-emphasis-color","currentcolor"),g.Nm(b,"webkit-text-emphasis","filled circle"),11===e.Ce||13===e.Ce)g.Nm(b,"webkit-text-emphasis-position","under left"),g.Nm(b,"text-emphasis-position","under left");c=!0;if(4===e.Ce||7===e.Ce||12===e.Ce||
14===e.Ce)g.Nm(k,"ruby-position","over"),g.Nm(k,"-webkit-ruby-position","before");else if(5===e.Ce||6===e.Ce||11===e.Ce||13===e.Ce)g.Nm(k,"ruby-position","under"),g.Nm(k,"-webkit-ruby-position","after"),c=!1;e=f?g.ci("DIV"):g.ci("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.Nm(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.Nm(f,"display","none"),f=f.nextElementSibling,g.Nm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Nm(k.lastElementChild,"display","none"),d?(g.Nm(k,"padding-top","0.6em"),g.Nm(f,"top","0")):(g.Nm(k,"padding-bottom","0.6em"),g.Nm(f,"bottom","0")));return k},h2=function(){g.G.apply(this,arguments)},i2=function(a){h2.call(this);
this.C=a;this.pens={};this.N={};this.X={};this.D="_"+g2++;this.K={};this.B=this.j=null;this.J=!0},j2=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},k2=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},l2=function(a,b){a=j2(a,b);
return void 0!==a?a:null},n2=function(a,b){a=a.getAttribute(b);
if(null!=a)return m2.test(a),a},QVa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.X[d]:a.C);a=l2(b,"mh");null!=a&&(c.Ut=a);a=l2(b,"ju");null!=a&&(c.textAlign=a);a=l2(b,"pd");null!=a&&(c.Xf=a);a=l2(b,"sd");null!=a&&(c.lI=a);a=n2(b,"wfc");null!=a&&(c.windowColor=a);b=j2(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},RVa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=l2(b,"ap");null!=a&&(c.Ci=a);a=j2(b,"cc");null!=a&&(c.Kn=a);a=j2(b,"ah");null!=a&&(c.oh=a);a=j2(b,"rc");null!=a&&(c.Wm=a);b=j2(b,"av");null!=b&&(c.hk=b);return c},SVa=function(a,b,c,d){var e={};
Object.assign(e,RVa(a,b));Object.assign(e,QVa(a,b));d?g.fg(e,a.C)?(d=a.D,e=a.C):d="_"+g2++:d=b.getAttribute("id")||"_"+g2++;a=j2(b,"t")+c;b=j2(b,"d")||0x8000000000000;if(2===e.Xf||3===e.Xf)c=e.Wm,e.Wm=e.Kn,e.Kn=c;return new f2(a,b,0,d,e)},o2=function(a){h2.call(this);
this.J=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},p2=function(a){a=g.Bh(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},TVa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Wm=a);b=b.ccColCount;void 0!==b&&(f.Kn=b);if(2===f.Xf||3===f.Xf)b=f.Wm,f.Wm=f.Kn,f.Kn=b;return new f2(c,d,0,e,f)},r2=function(){this.B=this.time=this.mode=this.u=0;
this.C=new q2(this);this.D=new q2(this);this.j=[];this.clear()},VVa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Xp:a,
Hn:b,result:0};a=UVa[a];b=UVa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Hn===d;if(d)return{Xp:a,Hn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Xp:a,Hn:b,result:2};return{Xp:a,Hn:b,result:3}},XVa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,WVa(a.C,b,c,d))},YVa=function(a,b){a.j.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.q(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?XVa(a,d.rL,d.sL,b):1===d.type&&a.u&496&&WVa(a.D,d.rL,d.sL,b);a.j.length=0},s2=function(){this.type=0},t2=function(){this.state=this.Hn=this.Xp=0},ZVa=function(){this.timestamp=this.j=0},u2=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new s2;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new ZVa}},v2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!==r.j){0===c&&(c=m,d=p);n=String.fromCharCode(r.j);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===r.j||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],r=p.j,0!==r&&(0===c&&(c=k,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},dWa=function(a,b){switch(a){case 0:return $Va[(b&127)-32];
case 1:return aWa[b&15];case 2:return bWa[b&31];case 3:return cWa[b&31]}return 0},w2=function(a){return a.B[a.row][a.u]},x2=function(a,b,c){2<=b&&1<a.u&&(--a.u,w2(a).j=0);
var d=w2(a);d.timestamp=a.D.time+0;d.j=dWa(b,c);32>a.u&&a.u++},eWa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.B[b+e][f],l=a.B[c+e][f];
k.j=l.j;k.timestamp=l.timestamp}},y2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},z2=function(a){a.row=0<a.j?a.j:1;
a.u=1;y2(a,0,15)},A2=function(a){this.B=a;
this.D=0;this.style=new s2;this.J=new u2(this.B);this.K=new u2(this.B);this.text=new u2(this.B);this.u=this.J;this.C=this.K;this.j=this.u},B2=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(v2(d,c),z2(a.u),z2(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(v2(d,c),y2(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},fWa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},gWa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},q2=function(a){this.j=a;
this.D=0;this.B=new A2(this.j);this.J=new A2(this.j);this.u=new t2;this.C=this.B},WVa=function(a,b,c,d){a.u.update();
b=VVa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Xp;c=b.Hn;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&x2(a,0,b),c&96&&x2(a,0,c),0!==b&&0!==c&&3===a.style.type&&v2(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Xp=e,b.Hn=c,b.state=2,b=e&8?a.J:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,k=1+d-c.j;eWa(c,k,f,c.j);b=f;e=c.j;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));y2(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:x2(b.j,0,32);break a;case 48:57===c?(d=b.j,w2(d).j=0,32>d.u&&d.u++):x2(b.j,1,c&15)}break;case 2:c&32&&x2(b.j,2,c&31);break;case 3:c&32&&x2(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:fWa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,w2(d).j=0);break;case 36:d=b.j;b=w2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:B2(b,2,d);break;case 38:B2(b,3,d);break;case 39:B2(b,4,d);break;case 40:x2(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);z2(d);gWa(b);break;case 43:gWa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:v2(a,d)}y2(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;v2(a,d);eWa(a,b,b+1,a.j-1);y2(a,a.row,1)}break;case 46:y2(b.C,0,15);break;case 47:v2(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,fWa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},hWa=function(){},C2=function(a,b,c){this.trackData=a;
this.J=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},D2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},E2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},F2=function(a,b){h2.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new r2;this.j.u=1<<this.track},G2=function(a){if("string"===typeof a)return!1;
a=new C2(a,8,0);return iWa(a)},iWa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==E2(a))return!1;
a.version=D2(a);if(1<a.version)return!1;D2(a);D2(a);D2(a);return!0},H2=function(){h2.call(this)},jWa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Oj=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3===p.nodeType)p=new e2(b,c,d,e.id,p.nodeValue,f||0<n,g.bg(l)?void 0:l),m.push(p),e.j.push(p);else{var r={};Object.assign(r,l);jWa(a,b,c,d,e,!0,p,r,m)}}},I2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},kWa=function(a,b,c,d){d=Object.assign({Ut:0},d);
return new f2(a,b,c,"_"+g2++,d)},J2=function(a,b){g.G.call(this);
this.I=a;this.Y=b;this.j=null;this.u=this.I.ut()},qWa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,k=lWa(a,b,d),l=[];try{for(var m=g.q(k),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.cI;l="string"!==typeof r?l.concat(mWa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(nWa(a,r,t)):l.concat(oWa(a,c,r,t))}var v=l}catch(x){g.S(x),a.clear(),v=[]}if(0!==v.length)return v}b=pWa(b);if(!b)return[];try{return"string"!==typeof b?mWa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?nWa(a,b,d):oWa(a,c,b,d)}catch(x){return g.S(x),a.clear(),[]}},pWa=function(a){if("string"===
typeof a||G2(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.Ey(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.py(a)},lWa=function(a,b,c){if("string"===typeof b||G2(b))return[{trackData:b,
cI:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.$ra(d);if(a.u&&e){var f=g.Tra(e);e=e.j;f&&e&&a.u.Fy(e,f)}f=g.Ny(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.q(f.entries());for(e=f.next();!e.done;e=f.next()){var k=g.q(e.value);e=k.next().value;k=k.next().value;k=new Uint8Array(b,k.dataOffset,k.size-(k.dataOffset-k.offset));k=g.py(k);a.push({trackData:k,cI:c+1E3*e})}rWa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},rWa=function(a,
b,c){var d=g.Ey(a,0,1836476516),e=9E4;
d&&(e=g.Fy(d)||9E4);d=0;var f=g.Ny(a,1836019558);f=g.q(f.entries());for(var k=f.next();!k.done;k=f.next()){var l=g.q(k.value);k=l.next().value;l=l.next().value;k<b.length&&(l=g.Ey(a,l.dataOffset,1953653094))&&(l=g.Ey(a,l.dataOffset,1952867444))&&(l=g.Ly(l)/e*1E3,0===k&&(d=l),b[k].cI=l-d+c||c*k*1E3)}},mWa=function(a,b,c,d,e){if(!G2(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new F2(e,b));return a.j.u(c,d)},nWa=function(a,b,c){a.j||(a.j=new H2);
a=a.j.u(b,c);.01>Math.random()&&g.Pv(Error("Deprecated subtitles format in web player: WebVTT"));return a},oWa=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new o2(sWa(b))),a.j.u(c,d)}catch(f){return g.S(f),[]}var e=g.u_(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new i2(sWa(b),a.Y)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},sWa=function(a){var b=
{};
if(a=g.ID(a))b.lang=a,g.URa.test(a)&&(b.Xf=1);return b},M2=function(a){g.vL.call(this,a);
var b=this;this.I=a;this.Y=this.I.V();this.videoData=this.I.getVideoData();this.Ya=this.I.eb();this.C={Ed:{}};this.D={Ed:{}};this.va=[];this.N={};this.Ia={};this.Z=!1;this.rb=g.HE(this.videoData);this.Wa=g.ACa(this.videoData,this.I);this.qb=!!this.videoData.captionTracks.length;this.xb=!!this.videoData.Lb;this.Ja="3"===this.Y.controlsType;this.u=this.J=this.K=this.Ea=this.Xa=null;this.Ra=new J2(this.I,this.Y);this.j=null;this.ma=new g.cA(this);this.Sa=new g.W({G:"div",L:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});var c=null,d=g.lq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.$p(d));this.storage=c;var e;this.ib=!(null==(e=a.yd())||!e.yy());this.B=tWa(this);this.X=!this.B&&this.Ja&&this.ib&&this.Wa;g.H(this,this.Ra);this.B?this.ya=this.xa=null:(this.xa=new g.vp(this.CI,void 0,this),g.H(this,this.xa),this.ya=new g.L(this.CZ,2E3,this),g.H(this,this.ya));g.H(this,this.ma);this.Y.S("caption_window_container_killswitch")||g.iL(this.player,this.Sa.element,4);
g.H(this,this.Sa);this.B||this.ma.T(a,"resize",this.FI);(this.jb=!g.dv()&&!this.I.isFullscreen()&&!this.B&&!this.X&&!this.Y.S("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.ma.T(a,"resize",this.tX);this.ma.T(a,"onPlaybackAudioChange",this.GW);this.ma.T(a,g.Hw("captions"),function(f){b.onCueRangeEnter(f)});
this.ma.T(a,g.Iw("captions"),function(f){b.onCueRangeExit(f)});
K2(this,L2(this)||{})},wWa=function(a){if(1===a.Y.Wa||1===a.videoData.Kv||"alwayson"===g.rE(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;var c=a.Y;if(g.ZC(c)&&c.S("web_player_prioritize_caption_visibility_on")&&("ON"===b||"on"===g.rE(a.videoData,"yt:cc")))return!0;if(2===a.Y.Wa){var d;g.cD(a.Y)?d=uWa(a):d=vWa(a,"module-enabled");if(null!=d)return!!d}c=V1(a.player.getAudioTrack(),W1(a.Y));d=g.rE(a.videoData,"yt:cc");if(void 0===N2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===
d;return"ON"===b||"on"===g.rE(a.videoData,"yt:cc")},O2=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},N2=function(a){var b=void 0,c=g.vs(g.us.getInstance(),65);
if(g.cD(a.Y)&&null!=c){if(null!=uWa(a))return!1;b=!c}return b},xWa=function(a){var b;
a.rb?b=new b2(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new Z1(a.videoData.j,a.player):a.qb?b=new g.zL(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.BL(a.Y,a.videoData.Lb,a.videoData.videoId,g.$wa(a.videoData),a.videoData.xj);return b},Q2=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.xb?!1:a.qb?!1:!0);b=g.wL(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.rE(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.ID(b[e])===c[d])return b[e];return a.J&&a.J.B?a.J.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||P2(a)}return null},P2=function(a){return a.J&&a.J.j},R2=function(a){var b=P2(a);
return!!b&&a.j===b},yWa=function(a){var b=V1(a.player.getAudioTrack(),W1(a.Y)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=Q2(a,a.Z):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&O2(a)?c=P2(a):N2(a)||a.Z||wWa(a)?c=Q2(a,a.Z):O2(a)&&(c=P2(a));if(a.B||a.X){var d=g.wL(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],k=g.ci("TRACK");k.setAttribute("kind","subtitles");k.setAttribute("label",g.GD(f));k.setAttribute("srclang",g.ID(f));k.setAttribute("id",f.toString());a.X||k.setAttribute("src",a.u.qq(f,"vtt"));f===c&&k.setAttribute("default","1");b.push(k)}c=a.I.yd();c.Pv(b);c=c.Je();
a.ib&&a.ma.T(c.textTracks,"change",a.SY)}else!a.j&&c&&S2(a,c),a.player.Pa("onCaptionsTrackListChanged"),a.player.Pa("onApiChange")},zWa=function(a,b){var c=a.I.yd().Je().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},S2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Z=c,a.Z&&(g.cD(a.Y)?T2(a,!!b):U2(a,"module-enabled",!!b)));a.j=b;O2(a)&&(a.j=P2(a));a.load()},AWa=function(a,b){a.Y.S("caption_window_container_killswitch")?g.iL(a.player,b,4):a.Sa.element.appendChild(b)},BWa=function(a,b){var c=a.Ya.getVideoContentRect(!0).height,d=a.Ya.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.ID(a.j):null;e&&g.URa.test(e)&&(b.params.Xf=1);e=a.Ya.getPlayerSize();switch(null!=b.params.Ut?b.params.Ut:1<b.j.length?1:0){case 1:return new c2(b,a.C,a.D,d,c,e.width,e.height,a.Y.experiments);case 2:return new d2(b,a.C,a.D,d,c,e.width,e.height,a.Y.experiments);default:return new a2(b,a.C,a.D,d,c,e.width,e.height,a.Y.experiments)}},K2=function(a,b,c){c=void 0===c?!1:c;
var d=V2.Ed;a.C={};Object.assign(a.C,V2);a.C.Ed={};Object.assign(a.C.Ed,d);a.D={Ed:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;m2.test(f);e.Ed.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;m2.test(f);e.Ed.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||V2.windowColor;m2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ed.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Ed.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Oj?3:d.bold?1:d.Oj?2:0);f=f.Ed;switch(e){case 1:f.bold=!0;delete f.Oj;break;case 2:delete f.bold;f.Oj=!0;break;case 3:f.bold=!0;f.Oj=!0;break;default:delete f.bold,delete f.Oj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ed.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=V2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ed.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ed.fontFamily=f;a.loaded&&a.FI();c&&(a.Y.S("web_player_local_storage_for_captions_setting_killswitch")?U2(a,"display-settings",b):g.cw("yt-player-caption-display-settings",b,2592E3))},W2=function(a,b,c){b&&!a.K?(b=NVa({Xf:0,
lang:"en-GB"}),a.K=[b,new e2(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.Qd(a.K)):!b&&a.K&&(CWa(a,a.K),a.K=null)},CWa=function(a,b){a.player.Vf(b);
g.xc(b,function(c){g.hc(this.va,c)},a);
g.wp(a.xa)},vWa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},U2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},T2=function(a,b){a.I.isInline()||g.cw("yt-player-sticky-caption",b,2592E3)},uWa=function(a){if(!a.I.isInline())return g.dw("yt-player-sticky-caption")},L2=function(a){return a.Y.S("web_player_local_storage_for_captions_setting_killswitch")?vWa(a,"display-settings"):g.dw("yt-player-caption-display-settings")},tWa=function(a){var b,c=!(null==(b=a.I.yd())||!b.wy());
return a.Ja&&c&&!a.Wa};
g.RP.prototype.Aw=g.da(35,function(a){var b=2;this.ya.has(a)?b=0:g.FFa(this,a)&&(b=1);return b});
g.xS.prototype.Aw=g.da(34,function(a){return this.ud.Aw(a)});
g.RP.prototype.Fy=g.da(33,function(a,b){this.Ra.set(a,b)});
g.xS.prototype.Fy=g.da(32,function(a,b){this.ud.Fy(a,b)});
g.PL.prototype.Ns=g.da(31,function(){this.Qa();for(var a=g.Wh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.gi(a[b])});
g.AP.prototype.Ns=g.da(30,function(){this.qa.Ns()});
g.PL.prototype.yy=g.da(29,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.AP.prototype.yy=g.da(28,function(){return this.qa.yy()});
g.PL.prototype.wy=g.da(27,function(){return!!this.j.textTracks});
g.AP.prototype.wy=g.da(26,function(){return this.qa.wy()});
g.PL.prototype.Pv=g.da(25,function(a){this.Qa();for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.AP.prototype.Pv=g.da(24,function(a){this.qa.Pv(a)});
g.yL.prototype.pH=g.da(23,function(){return!1});
g.yL.prototype.Oo=g.da(22,function(){});
g.zL.prototype.Oo=g.da(21,function(a,b,c){var d=this;this.isDisposed();b=this.qq(a,b);this.jn();this.j=g.Jr(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.BL.prototype.Oo=g.da(20,function(a,b,c){var d=this;this.isDisposed();b=this.qq(a,b);this.jn();this.j=g.Jr(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.hS.prototype.Mw=g.da(8,function(){return this.C});
g.NU.prototype.Mw=g.da(7,function(){var a;return(null==(a=g.kL(this))?void 0:a.ut())||null});
g.bL.prototype.ut=g.da(6,function(){return this.app.Mw()});
g.nU.prototype.ut=g.da(5,function(){var a;return(null==(a=this.Va)?void 0:a.Mw())||null});
var yVa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bh:"Bhojpuri",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",
cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",swc:"Congo Swahili",
syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",
uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};X1.prototype.contains=function(a){a=g.qc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
X1.prototype.length=function(){return this.segments.length/2};
g.w(Y1,g.G);g.h=Y1.prototype;g.h.ra=function(){g.G.prototype.ra.call(this);this.B&&this.B.cancel()};
g.h.qB=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.rd();var b=this.j;this.j=g.Zb(this.Z.xm(a).j);b!==this.j&&this.X&&this.X()};
g.h.reset=function(){this.C=new X1;this.J=-1;this.B&&(this.B.cancel(),this.B=null)};
g.h.xN=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.xn(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.wv(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.ut();if(c){var d=a.j[0].Na;if(b=c.Zk(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Aw(d),0===c)b&&(a.B=new g.Wx(b));else if(2===c){this.K.start();wVa(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Na)||
xVa(this,a),this.j=g.Zb(a.j)):!this.Y.S("force_caption_seek_for_live_killswitch")&&wVa(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.h.Qa=function(){};
g.w(Z1,g.yL);g.h=Z1.prototype;g.h.Oo=function(a,b,c){var d=this;this.jn();b=AVa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?BVa(this,b,"386"):BVa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.yCa(this.Y);this.B=new Y1(f,this.I,b,function(k,l){c(k,a,l,e)},this.J||g.Mz(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.h.pH=function(){var a=this.D;this.D=!1;return a};
g.h.Pt=function(a){var b=this.J?[new g.FD({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.FD({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?zVa(this,"386"):zVa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.xL(this.u,c.value);a()};
g.h.jn=function(){this.B&&(this.B.dispose(),this.B=null)};
g.h.qq=function(){return""};
var m2=/^#(?:[0-9a-f]{3}){1,2}$/i,DVa=/#(.)(.)(.)/,CVa=/^#(?:[0-9a-f]{3}){1,2}$/i;var FVa=["left","right","center","justify"];g.w(a2,g.W);g.h=a2.prototype;g.h.uS=function(a,b){var c=g.Wm(this.element,this.element.parentElement);this.Xa=a-c.x;this.Ya=b-c.y;g.M(this.element,"ytp-dragging")};
g.h.tS=function(a,b){var c=g.Ym(this.element);a=a-this.Xa-.02*this.playerWidth;var d=b-this.Ya-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Bh(e,0,2));var f=(d+c.height/2)/this.Sa*3;f=Math.floor(g.Bh(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Bh(a,0,1);c=(d+f/2*c.height)/this.Sa;c=100*g.Bh(c,0,1);this.u.params.Ci=b;this.u.params.hk=c;this.u.params.oh=a;this.j.Ci=b;this.j.hk=c;this.j.oh=a;this.Ia.Ci=b;this.Ia.hk=c;this.Ia.oh=a;this.zP()};
g.h.sS=function(){g.Fp(this.element,"ytp-dragging")};
g.h.zP=function(){this.Gu(this.D)};
g.h.getType=function(){return this.type};
g.h.Gu=function(a){var b=Math.min(this.kM(),this.maxWidth),c=this.jM(),d="";3===this.u.params.Xf&&(d="rotate(180deg)");g.Nm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.fE(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.oh+2;d=this.j.Ci;switch(d){case 0:case 3:case 6:(b=this.j.Ed.fontSizeIncrement)&&0<b&&2!==this.j.Xf&&3!==
this.j.Xf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.hk+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Nm(this.element,
a)};
g.h.fE=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.xa||this.D.length>b)b=0,this.xa=!1,this.D=[],this.J=this.Ea=this.ya=null,g.ei(this.C);for(;b<a.length;b++)JVa(this,a[b])};
g.h.kM=function(){return 0};
g.h.jM=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};g.w(b2,g.yL);b2.prototype.Oo=function(a,b,c){uVa(this.videoData.videoId,a.vssId,c)};
b2.prototype.Pt=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.xL(this.u,c.value);a()};g.w(c2,a2);c2.prototype.fE=function(a){var b=this.u.j;a2.prototype.fE.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,DWa);var e=c.j;var f=d}JVa(this,c,d)}};
var DWa={jV:!0};g.w(d2,a2);g.h=d2.prototype;g.h.zP=function(){g.yp(this.Ra)};
g.h.kY=function(){g.Fp(this.element,"ytp-rollup-mode");this.Gu(this.qb,!0)};
g.h.jM=function(){return this.B?this.X:this.N};
g.h.kM=function(){return this.B?this.N:this.X};
g.h.Gu=function(a,b){this.qb=a;if(this.u.params.Wm){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ib=this.X;this.N=this.X=0;a2.prototype.Gu.call(this,a);MVa(this,b)}a2.prototype.Gu.call(this,a)};g.w(e2,g.Fw);e2.prototype.toString=function(){return g.Fw.prototype.toString.call(this)};g.w(f2,g.Fw);f2.prototype.toString=function(){return g.Fw.prototype.toString.call(this)};
var g2=0;g.w(h2,g.G);h2.prototype.u=function(){return[]};
h2.prototype.reset=function(){};g.w(i2,h2);i2.prototype.reset=function(){this.K={};this.B=this.j=null;this.J=!0};
i2.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,k={},l=a.getAttribute("p");l&&Object.assign(k,this.pens[l]);l=k2(a,"b");
null!=l&&(k.bold=l);l=k2(a,"i");null!=l&&(k.Oj=l);l=k2(a,"u");null!=l&&(k.underline=l);l=l2(a,"et");null!=l&&(k.charEdgeStyle=l);l=l2(a,"of");null!=l&&(k.offset=l);l=n2(a,"bc");null!=l&&(k.background=l);l=n2(a,"ec");null!=l&&(k.tE=l);l=n2(a,"fc");null!=l&&(k.color=l);l=l2(a,"fs");null!=l&&0!==l&&(k.fontFamily=l);l=j2(a,"sz");void 0!==l&&(k.fontSizeIncrement=l/100-1);l=j2(a,"bo");void 0!==l&&(k.backgroundOpacity=l/255);l=j2(a,"fo");void 0!==l&&(k.textOpacity=l/255);l=l2(a,"rb");null!=l&&10!==l&&0!==
l&&(k.Ce=10<l?l-1:l);a=l2(a,"hg");null!=a&&(k.MM=a);f[c]=k;break;case "ws":c=a.getAttribute("id");this.X[c]=QVa(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=RVa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=SVa(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;k=
!!k2(a,"a");l=(j2(a,"t")||0)+l;var m=j2(a,"d")||5E3;k||(!this.J&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=k?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var v=r[t],x=void 0;0<t&&(k=!0);var y=void 0;1===v.nodeType&&(y=v);if(y&&"s"===y.tagName){if((v=(v=y.getAttribute("p"))?this.pens[v]:null)&&v.Ce&&(1===v.Ce?(v=r.slice(t,t+4),
4===v.length&&(x=PVa(l,m,f,k,n,v,this.pens),t+=3)):x=PVa(l,m,f,k,n,[y],this.pens)),!x){var z=y;x=l;y=m;v=f;var E=k,I=n,J=z.textContent?z.textContent:"",N=z.getAttribute("p");N=N?this.pens[N]:null;z=j2(z,"t")||0;x=new e2(x+z,y-z,I,v,J,E,N)}}else x=new e2(l,m,n,f,v.textContent||"",k,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=SVa(this,a,b,!0),d.push(this.j)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];return b};var EWa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(o2,h2);o2.prototype.reset=function(){this.B.clear()};
o2.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},k=e.pParentId;k&&Object.assign(f,this.j.get(k));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Oj=!0);e.uAttr&&(f.underline=!0);k=e.ofOffset;null!=k&&(f.offset=k);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);k=e.etEdgeType;null!=k&&(f.charEdgeStyle=k);void 0!==e.ecEdgeColor&&(f.tE=p2(e.ecEdgeColor));k=e.fsFontStyle;null!=k&&0!==k&&(f.fontFamily=
k);void 0!==e.fcForeColor&&(f.color=p2(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=p2(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(k=e.rbRuby)&&10!==k&&(f.Ce=10<k?k-1:k,f.gk=EWa.get(f.Ce));e.hgHorizGroup&&(f.MM=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wsParentId)?Object.assign(f,this.D.get(k)):Object.assign(f,
this.J),void 0!==e.mhModeHint&&(f.Ut=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Xf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.lI=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=p2(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wpParentId)&&Object.assign(f,this.C.get(k)),void 0!==e.ahHorPos&&
(f.oh=e.ahHorPos),void 0!==e.apPoint&&(f.Ci=e.apPoint),void 0!==e.avVerPos&&(f.hk=e.avVerPos),void 0!==e.ccCols&&(f.Kn=e.ccCols),void 0!==e.rcRows&&(f.Wm=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=TVa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+g2++,k=TVa(this,l,d,e,f),a.push(k),this.B.set(f,k));0===e&&(e=5E3);k=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],v=t.utf8;if(v){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.j.get(t.pPenId));if(2===(null!=k.params.Ut?k.params.Ut:1<k.j.length?1:0)&&m&&"\n"===v)continue;if(t=y&&1===y.Ce)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.j.get(z))&&z.Ce&&2===z.Ce?(z=p[t+2].pPenId,z=this.j.get(z),!z||!z.Ce||3>z.Ce?t=!1:(z=p[t+3].pPenId,t=(z=this.j.get(z))&&
z.Ce&&2===z.Ce?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);v=OVa(v,x,z,t,E);m=new e2(d,e,n,f,v,m,y);l+=3}else m=new e2(d+x,e-x,n,k.id,v,m,y||r);m&&(a.push(m),k.j.push(m))}m=!0}}}b=a}else b=[];return b};r2.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
r2.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var UVa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];s2.prototype.set=function(a){this.type=a};
s2.prototype.get=function(){return this.type};
t2.prototype.clear=function(){this.state=0};
t2.prototype.update=function(){this.state=2===this.state?1:0};
t2.prototype.isValid=function(){return 0!==this.state};
t2.prototype.matches=function(a,b){return this.isValid()&&a===this.Xp&&b===this.Hn};
ZVa.prototype.reset=function(){this.timestamp=this.j=0};
u2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
u2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
u2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var $Va=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],aWa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],bWa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],cWa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];A2.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.J;this.C=this.K;this.j=this.u;var c=(a<<2)+(b<<1);this.J.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
q2.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.J.reset(a,1)};hWa.prototype.C=function(){};g.w(C2,hWa);C2.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+g2++;c=c/1E3-this.J;d=d/1E3-this.J;a=new f2(c,d-c,5,f,{textAlign:0,Ci:0,oh:2.5*b,hk:5.33*a});e=new e2(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(F2,h2);F2.prototype.u=function(a){a=new C2(a,a.byteLength,this.B);if(iWa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=E2(a)*(1E3/45):1===a.version&&(a.B=4294967296*E2(a)+E2(a)),a.D=D2(a);0<a.D;a.D--){var b=D2(a),c=D2(a),d=D2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,rL:c,sL:d,order:b.j.length}))}YVa(this.j,a);return a.u}return[]};
F2.prototype.reset=function(){this.j.clear()};g.w(H2,h2);
H2.prototype.u=function(a,b){var c=[];a=a.split(FWa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!GWa.test(e)){var k=X2.exec(e);if(k&&4<=k.length){var l=I2(k[1]),m=I2(k[2])-l;l+=f;var n=(k=k[3])?k.split(" "):[];k={};var p=null;var r="";var t=null,v="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],k.hk=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];k.oh=Number.parseInt(t,10);2===x.length&&(v=x[1].trim());break;case "align":switch(y){case "start":k.textAlign=0;break;case "middle":k.textAlign=2;break;case "end":k.textAlign=1}}}p||r||(r="end");if(!t)switch(k.textAlign){case 0:k.oh=0;break;case 1:k.oh=100;break;case 2:k.oh=50}if(null!=k.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(k.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;k.Ci=r}e=e.substring(X2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=k;k=e;e={};if(0>k.indexOf("<")&&0>k.indexOf("&"))f=kWa(l,m,5,v),m=new e2(l,m,5,f.id,k,!1,g.bg(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(r=k.split(HWa),1===r.length?(k=5,v=kWa(l,m,k,v)):(p=k=6,v=Object.assign({Kn:32},v),v=new f2(l,m,p,"_"+g2++,v)),c.push(v),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.u_("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,jWa(this,p,m-(p-l),k,v,0<t,y,e,c)):p=I2(n)+f}X2.lastIndex=0}}return c};
var GWa=/^NOTE/,FWa=/(?:\r\n|\r|\n){2,}/,X2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),HWa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.DP.HA(H2,{u:"wvppt"});g.w(J2,g.G);J2.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
J2.prototype.reset=function(){this.j&&this.j.reset()};
J2.prototype.ra=function(){g.G.prototype.ra.call(this);this.clear()};var V2={windowColor:"#080808",windowOpacity:0,textAlign:2,Ci:7,oh:50,hk:100,Ed:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(M2,g.vL);g.h=M2.prototype;g.h.ra=function(){if(this.B||this.X){var a=this.I.yd();a&&!a.isDisposed()&&a.Ns()}else W2(this,!1);g.vL.prototype.ra.call(this)};
g.h.qr=function(){if(this.Ja)return this.B||this.X;var a=V1(this.player.getAudioTrack(),W1(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?O2(this):N2(this)||O2(this)?!0:wWa(this)};
g.h.load=function(){var a=this;g.vL.prototype.load.call(this);var b=!this.Y.S("web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.j&&(this.Ra.clear(),this.B?zWa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Oo(this.j,"json3",function(c,d,e,f){c&&(a.u.pH()&&(a.va=[],a.I.kf("captions"),g.wp(a.xa),a.Ra.reset()),c=qWa(a.Ra,c,d,e,f),a.player.Qd(c,void 0,a.Wa),!a.Z||a.X||R2(a)||g.PC(a.Y)||g.IC(a.Y)||(g.zp(a.ya),c=NVa({Ci:0,oh:5,hk:5,Wm:2,textAlign:0,
Xf:0,lang:"en-GB"}),a.Ea=[c],d=["Click "," for settings"],a.Xa||(e=new g.pI(g.GI()),g.H(a,e),a.Xa=e.element),e=c.end-c.start,(f=g.GD(a.j))&&a.Ea.push(new e2(c.start,e,0,c.id,f)),a.Ea.push(new e2(c.start,e,0,c.id,d[0]),new e2(c.start,e,0,c.id,a.Xa,!0),new e2(c.start,e,0,c.id,d[1],!0)),a.player.Qd(a.Ea),g.xp(a.ya)),!a.Z||a.X||R2(a)||(g.cD(a.Y)?T2(a,!0):U2(a,"module-enabled",!0),a.J&&(a.J.C=a.j),a.player.Ar()),a.Z=!1)}),!b||this.B||this.X||R2(this)||this.player.Pa("captionschanged",g.HD(this.j))),b||
(this.j&&!R2(this)?this.player.Pa("captionschanged",g.HD(this.j)):this.player.Pa("onCaptionsTrackListChanged"))):(this.u=xWa(this),g.H(this,this.u),this.u.Pt(function(){yWa(a)}))};
g.h.unload=function(){this.B&&this.j?zWa(this,!1):(this.ya&&g.zp(this.ya),this.player.kf("captions"),this.va=[],this.u&&this.u.jn(),this.Ra.clear(),this.K&&this.player.Qd(this.K),this.FI());g.vL.prototype.unload.call(this);this.player.Ar();this.player.Pa("captionschanged",{})};
g.h.create=function(){this.qr()&&this.load()};
g.h.SY=function(){for(var a=this.I.yd().Je().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.wL(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&S2(this,b,!0)};
g.h.z_=function(){!this.j&&this.B||this.unload()};
g.h.onCueRangeEnter=function(a){this.va.push(a);g.wp(this.xa)};
g.h.onCueRangeExit=function(a){g.hc(this.va,a);this.u instanceof Z1&&this.u.J&&this.player.Vf([a]);g.wp(this.xa)};
g.h.uZ=function(a){if(a instanceof f2){var b=this.N[a.id];b&&b.u!==a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=BWa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.Ia[b]||(this.Ia[b]=[]),this.Ia[b].push(a)};
g.h.getCaptionWindowContainerId=function(){return this.Sa.element.id};
g.h.CZ=function(){CWa(this,this.Ea);this.Ea=null};
g.h.CI=function(){var a=this;if(!this.jb||!this.B){this.xa.stop();g.cg(this.Ia);this.va.sort(g.Gw);var b=this.va;if(this.K){var c=g.Wn(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.xc(b,this.uZ,this);g.Nf(this.N,function(d,e){a.Ia[e]?(d.element.parentNode||(d instanceof d2||d instanceof c2||g.Sf(a.N,function(f,k){k!==e&&f.u.params.Ci===d.u.params.Ci&&f.u.params.oh===d.u.params.oh&&f.u.params.hk===d.u.params.hk&&(f.dispose(),delete a.N[k]);return k===e},a),AWa(a,d.element)),d.Gu(a.Ia[e])):(d.dispose(),delete a.N[e])},this)}};
g.h.GZ=function(){K2(this,{},!0);this.Y.S("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Pa("captionssettingschanged")};
g.h.HU=function(){var a=V2.Ed;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Oj?3:a.bold?1:a.Oj?2:0,textOpacity:a.textOpacity,windowColor:V2.windowColor,windowOpacity:V2.windowOpacity};var b=L2(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.BQ=function(a,b){var c={};Object.assign(c,L2(this));Object.assign(c,a);K2(this,c,b);this.player.Pa("captionssettingschanged")};
g.h.FI=function(){!this.B&&this.loaded&&(g.Nf(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.CI())};
g.h.yf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Bh(b,-2,4);this.BQ({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&S2(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.B&&(g.cD(this.Y)?T2(this,!!b):U2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ra(b))break;if(g.bg(b)){S2(this,null,!0);break}a=g.wL(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?tVa(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.Vta(),a=g.ID(c),b.length&&a===b[b.length-1]||(b.push(a),g.cw("yt-player-caption-language-preferences",b)),S2(this,c,!0))}else return this.loaded&&this.j&&!R2(this)?g.HD(this.j):{};return"";case "tracklist":return this.u?g.Zl(g.wL(this.u.u,!(!b||!b.includeAsr)),function(f){return g.HD(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||W2(this,!!b);break;case "sampleSubtitlesCustomized":this.B||W2(this,!!b,b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.B&&a.push("stickyLoading");return a};
g.h.vF=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.S("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.ID(a));return{cc:b}}return{}};
g.h.o_=function(){this.loaded&&this.j&&!R2(this)?(g.cD(this.Y)?T2(this,!1):U2(this,"module-enabled",!1),this.unload(),O2(this,!0)&&S2(this,P2(this),!1)):this.jQ()};
g.h.jQ=function(){this.loaded&&this.j&&!R2(this)||S2(this,R2(this)||!this.j?Q2(this,!0):this.j,!0)};
g.h.GW=function(){var a=R2(this);O2(this,a)?S2(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.qr()&&(a?S2(this,Q2(this),!1):this.load()))};
g.h.tX=function(){var a=this.I.yd();a&&!a.isDisposed()&&a.Ns();this.I.isFullscreen()?(this.B=this.Ja=!0,this.loaded&&yWa(this)):(this.Ja="3"===this.Y.controlsType,this.B=tWa(this));S2(this,this.j)};
g.DP.HA(M2,{CI:"smucd"});g.uL("captions",M2);})(_yt_player);
