(function(g){var window=this;'use strict';var OWa=function(a,b){a.Pa("onAutonavCoundownStarted",b)},l3=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Se(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.vD&&(b.lengthText?(e=b.lengthText||null,f=b.Hq||null):b.lengthSeconds&&(e=g.rJ(b.lengthSeconds),f=g.rJ(b.lengthSeconds,!0)));var k=!!d;d=k&&"RD"===g.rD(d).type;var l=b instanceof g.vD?b.isLivePlayback:null,m=b instanceof g.vD?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.cm||g.SF("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.il(),is_live:l,is_upcoming:m,is_list:k,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Gn};b instanceof g.uD&&(c.playlist_length=b.playlistLength);a.update(c)},m3=function(a){var b=a.V(),c=b.j;
g.W.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",
Ga:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",oa:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],oa:"{{title}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],oa:"{{author}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],oa:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=
null;this.j=c;this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress)},o3=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.J=b;this.D=void 0;this.u=0;b=a.V();var d=b.j;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",oa:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.J:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",Ga:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"}]},
{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",oa:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",oa:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",oa:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",oa:"{{author_and_views}}"}]}]}]});g.H(this,this.j);this.j.Ba(this.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.TJ);this.I.Bb(this.element,
this,115127);this.I.Bb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.B=new g.W({G:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ba(this.element);this.cancelButton=new g.W({G:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);
this.cancelButton.Ba(this.B.element);this.cancelButton.Oa("click",this.zS,this);this.I.Bb(this.cancelButton.element,this,115129);this.playButton=new g.W({G:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},oa:"Play now"});g.H(this,this.playButton);this.playButton.Ba(this.B.element);this.playButton.Oa("click",this.TJ,this);this.I.Bb(this.playButton.element,this,115130);this.C=new g.L(function(){n3(c)},
500);
g.H(this,this.C);this.SJ();this.T(a,"autonavvisibility",this.SJ)},r3=function(a){var b=a.I.Jj(!0,a.I.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.Df(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.fC);g.O(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Ae());g.O(a.I.getRootNode(),"countdown-running",a.Qh());g.O(a.element,"ytp-player-content",a.I.Ae());g.Nm(a.overlay.element,{width:b.width+"px"});if(!a.Qh()){a.I.Ae()?p3(a,Math.round(q3(a)/1E3)):p3(a);b=!!a.suggestion&&!!a.suggestion.Gn;var c=a.I.Ae()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.sI(a.B,a.I.Ae())}},n3=function(a){var b=q3(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);p3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Qh()?a.select(!0):a.Qh()&&a.C.start()},q3=function(a){var b=a.I.kq();
return 0<=b?b:g.XA(a.I.V().experiments,"autoplay_time")||1E4},p3=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.ei(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.di("Up next in $SECONDS".slice(0,d)));var e=g.ci("span");g.Cp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ji(e,b);a.appendChild(e);a.appendChild(g.di("Up next in $SECONDS".slice(d+c.length)));return}}g.ji(a,"Up next")},s3=function(a,b){g.W.call(this,{G:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},t3=function(a){g.W.call(this,{G:"div",
Ga:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",oa:"Up Next"},{G:"span",L:"ytp-upnext-title",oa:"{{title}}"},{G:"span",L:"ytp-upnext-author",oa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
oa:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.L(this.Iz,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.W({G:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Oa("click",this.AS,this);this.cancelButton.Ba(b);this.cancelButton&&this.api.Bb(this.cancelButton.element,
this,115129);g.H(this,this.C);this.api.Bb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.BS);this.api.Bb(b,this,115130);this.UJ();this.T(a,"autonavvisibility",this.UJ);this.T(a,"mdxnowautoplaying",this.vX);this.T(a,"mdxautoplaycanceled",this.wX);g.O(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},PWa=function(a,b){return b?b:0<=a.api.kq()?a.api.kq():g.XA(a.api.V().experiments,"autoplay_time")||1E4},u3=function(a,b){b=PWa(a,b);
var c=Math,d=c.min;var e=(0,g.R)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Qh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Qh()&&a.j.start()},v3=function(a){s3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],oa:"More videos"}]});this.K=new g.W({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new o3(this.player);g.H(this,this.u);this.u.Ba(this.element);a.getVideoData().lc?this.j=this.u:(this.j=new t3(a),g.iL(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.W({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.C=new g.cA(this);g.H(this,this.C);g.H(this,this.table);this.table.Ba(this.element);this.table.show();g.H(this,this.K);this.K.Ba(this.table.element);this.hide()},w3=function(a){var b=a.Ae();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},x3=function(a){s3.call(this,a,"subscribecard-endscreen");
this.j=new g.W({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",oa:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.Ba(this.element);var b=a.getVideoData();this.subscribeButton=new g.AM("Subscribe",null,"Unsubscribe",null,!0,!1,b.sj,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ba(this.j.Da("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ka);this.Ka();this.hide()},y3=function(a){var b=a.V(),c=g.gA||g.yC?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",Ga:e,W:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",W:c,U:[{G:"span",L:"ytp-videowall-still-info-title",oa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",oa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",oa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",oa:"{{duration}}"}]}]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",oa:"{{playlist_length}}"},")"]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",oa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.cA(this);g.H(this,this.j);this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.ah(this.element,this);this.onVideoDataChange()},z3=function(a){s3.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.N=null;this.u=new g.cA(this);g.H(this,this.u);this.J=new g.L(function(){g.M(b.element,"ytp-show-tiles")},0);
g.H(this,this.J);var c=new g.W({G:"button",Ga:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},U:[g.xI()]});g.H(this,c);c.Ba(this.element);c.Oa("click",this.GS,this);this.table=new g.pI({G:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ba(this.element);c=new g.W({G:"button",Ga:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},U:[g.yI()]});g.H(this,c);c.Ba(this.element);c.Oa("click",this.ES,this);a.getVideoData().lc?this.j=new o3(a,!0):this.j=new t3(a);
g.H(this,this.j);g.iL(this.player,this.j.element,4);this.hide()},A3=function(a){return g.jL(a.player)&&a.Rv()&&!a.C},B3=function(a){var b=a.Ae();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},C3=function(a){g.vL.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.cA(this);g.H(this,this.listeners);this.env=a.V();QWa(a)?(this.B=!0,RWa(this),this.j?this.endScreen=new v3(a):this.endScreen=new z3(this.player)):this.env.Sd?this.endScreen=new x3(this.player):this.endScreen=new s3(this.player);g.H(this,this.endScreen);g.iL(this.player,this.endScreen.element,4);SWa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.Hw("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.Iw("endscreen"),function(c){b.onCueRangeExit(c)})},RWa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Sh&&a.u===b.lc)return!1;a.j=b.Sh;a.u=b.lc;return!0},QWa=function(a){a=a.V();
return!a.K&&a.Lb&&!a.Sd},SWa=function(a){a.player.kf("endscreen");
var b=a.player.getVideoData();b=new g.Fw(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Fw(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Qd([b,c])};
g.bL.prototype.kq=g.da(4,function(){return this.app.kq()});
g.NU.prototype.kq=g.da(3,function(){return this.getVideoData().mP});g.w(m3,g.W);m3.prototype.select=function(){(this.I.qk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.ow||void 0)||this.I.S("web_player_endscreen_double_log_fix_killswitch"))&&this.I.wb(this.element)};
m3.prototype.onClick=function(a){g.UL(a,this.I,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.zu(a)||(this.select(),g.yu(a))}};g.w(o3,g.W);g.h=o3.prototype;g.h.fz=function(a){this.suggestion!==a&&(this.suggestion=a,l3(this.j,a),this.playButton.Ma("url",this.suggestion.il()),r3(this))};
g.h.Qh=function(){return 0<this.u};
g.h.Hu=function(){this.Qh()||(this.u=Date.now(),n3(this),OWa(this.I,q3(this)),g.O(this.I.getRootNode(),"countdown-running",this.Qh()))};
g.h.Sq=function(){this.hn();n3(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.ji(a,"Up next")};
g.h.hn=function(){this.Qh()&&(this.C.stop(),this.u=0)};
g.h.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.hn()};
g.h.TJ=function(a){g.UL(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.wb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.I.bb(a,!0),this.I.wb(a)),this.select())};
g.h.zS=function(){this.I.wb(this.cancelButton.element);g.dL(this.I,!0);this.D&&this.I.Pa("innertubeCommand",this.D)};
g.h.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.T_)?void 0:c.command};
g.h.SJ=function(){var a=this.I.Ae();this.J&&this.ub!==a&&g.sI(this,a);r3(this);this.I.bb(this.element,a);this.I.bb(this.cancelButton.element,a);this.I.bb(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.I.bb(this.playButton.element,a)};
g.h.Df=function(a){return 400>a.width||459>a.height};g.w(s3,g.W);g.h=s3.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Rv=function(){return!1};
g.h.Ae=function(){return!1};
g.h.iN=function(){return!1};g.w(t3,g.W);g.h=t3.prototype;g.h.Iz=function(){this.notification&&(this.C.stop(),this.wc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.h.fz=function(a){this.suggestion=a;l3(this,a,"hqdefault.jpg")};
g.h.UJ=function(){g.sI(this,this.api.Ae());this.api.bb(this.element,this.api.Ae());this.api.bb(this.Da("ytp-upnext-autoplay-icon"),this.api.Ae());this.cancelButton&&this.api.bb(this.cancelButton.element,this.api.Ae())};
g.h.EX=function(){window.focus();this.Iz()};
g.h.Hu=function(a){var b=this;this.Qh()||(g.Nu("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.R)(),this.j=new g.L(function(){u3(b,a)},25),u3(this,a),OWa(this.api,PWa(this,a)));
g.Fp(this.element,"ytp-upnext-autoplay-paused")};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Qh=function(){return!!this.j};
g.h.Sq=function(){this.hn();this.u=(0,g.R)();u3(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.h.hn=function(){this.Qh()&&(this.j.dispose(),this.j=null)};
g.h.select=function(a){a=void 0===a?!1:a;if(this.api.V().S("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Iz(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Se()}),this.B=this.T(this.notification,"click",this.EX),this.C.start())}this.hn();this.api.nextVideo(!1,a)};
g.h.BS=function(a){!g.ii(this.cancelButton.element,g.uu(a))&&g.UL(a,this.api)&&(this.api.Ae()&&this.api.wb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.h.AS=function(){this.api.Ae()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.dL(this.api,!0)};
g.h.vX=function(a){this.api.getPresentingPlayerType();this.show();this.Hu(a)};
g.h.wX=function(){this.api.getPresentingPlayerType();this.hn();this.hide()};
g.h.ra=function(){this.hn();this.Iz();g.W.prototype.ra.call(this)};g.w(v3,s3);g.h=v3.prototype;g.h.create=function(){s3.prototype.create.call(this);this.C.T(this.player,"appresize",this.Ev);this.C.T(this.player,"onVideoAreaChange",this.Ev);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.VJ);this.C.T(this.player,"autonavcancel",this.CS);this.onVideoDataChange()};
g.h.show=function(){s3.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.dL(this.player,!1);g.jL(this.player)&&this.Rv()&&!this.B?(w3(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Hu():3===this.videoData.autonavState&&this.j.Sq()):(g.dL(this.player,!0),w3(this));this.Ev()};
g.h.hide=function(){s3.prototype.hide.call(this);this.j.Sq();w3(this)};
g.h.Ev=function(){var a=this.player.Jj(!0,this.player.isFullscreen());w3(this);r3(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.Df(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.NA(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Nm(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.q(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.j.fz(a[0]);this.j!==this.u&&this.u.fz(a[0]);for(var b=0;b<TWa.length;++b){var c=TWa[b];if(a&&a[c]){this.videos[b]=new m3(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l3(d,c));g.H(this,this.videos[b]);this.videos[b].Ba(this.K.element)}}}this.Ev()}};
g.h.VJ=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.hn(),this.ub&&this.Ev()):(this.J=!0,this.Ae()&&(2===a?this.j.Hu():3===a&&this.j.Sq()))};
g.h.CS=function(a){a?this.VJ(1):(this.B=null,this.J=!1)};
g.h.Rv=function(){return 1!==this.videoData.autonavState};
g.h.Df=function(a){return(910>a.width||459>a.height)&&!this.NA(a)&&!(400>=a.width||360>=a.height)};
g.h.NA=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.h.Ae=function(){return this.ub&&g.jL(this.player)&&this.Rv()&&!this.B};
var TWa=[1,3,2,4];g.w(x3,s3);x3.prototype.Ka=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.sj;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(y3,g.W);y3.prototype.select=function(){(this.api.qk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.ow||void 0)||this.api.S("web_player_endscreen_double_log_fix_killswitch"))&&this.api.wb(this.element)};
y3.prototype.onClick=function(a){g.UL(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
y3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.zu(a)||(this.select(),g.yu(a))}};
y3.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.j};g.w(z3,s3);g.h=z3.prototype;g.h.create=function(){s3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Ol();this.u.T(this.player,"appresize",this.Ol);this.u.T(this.player,"onVideoAreaChange",this.Ol);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.pD);this.u.T(this.player,"autonavcancel",this.DS);a=this.videoData.autonavState;a!==this.N&&this.pD(a);this.u.T(this.element,"transitionend",this.TY)};
g.h.destroy=function(){g.jv(this.u);g.Bf(this.stills);this.stills=[];s3.prototype.destroy.call(this);g.Fp(this.element,"ytp-show-tiles");this.J.stop();this.N=this.videoData.autonavState};
g.h.Rv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){s3.prototype.show.call(this);g.Fp(this.element,"ytp-show-tiles");this.player.V().isMobile?g.yp(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.dL(this.player,!1);A3(this)?(B3(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Hu():3===this.videoData.autonavState&&this.j.Sq()):(g.dL(this.player,!0),B3(this))};
g.h.hide=function(){s3.prototype.hide.call(this);this.j.Sq();B3(this)};
g.h.TY=function(a){g.uu(a)===this.element&&this.Ol()};
g.h.Ol=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.I.Jj(!0,this.I.isFullscreen()),b=g.ZK(this.I);b&&(b=b.Ze()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,v=e<=k-2&&n>=p*m;if((p+
1)/r*d/c>c/(p/(r+1)*d)&&v)n-=p*m,e+=2;else if(t)n-=r*m,b+=2;else if(v)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Xm(a,m,n);g.Nm(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.fz(this.videoData.suggestions[0]);this.j instanceof o3&&r3(this.j);g.O(this.element,"ytp-endscreen-takeover",A3(this));B3(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(r=c,p=0,d&&f>=b-2&&k>=e-2?p=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(p=2):p=2),r=g.Ch(r+this.B,l),0!==p){t=this.stills[c];t||(t=new y3(this.player),this.stills[c]=t,a.appendChild(t.element));v=Math.floor(n*k/e);var x=Math.floor(m*f/b),y=Math.floor(n*(k+p)/e)-v-4,z=Math.floor(m*(f+p)/b)-x-4;g.Tm(t.element,x,v);g.Xm(t.element,z,y);g.Nm(t.element,"transitionDelay",(k+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===p);g.O(t.element,"ytp-videowall-still-large",
2<p);p=t;r=this.videoData.suggestions[r];p.suggestion!==r&&(p.suggestion=r,t=p.api.V(),v=g.Dp(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l3(p,r,v),g.AC(t)&&(v=r.il(),x={},t.xa&&g.wK(x,t.loaderUrl),v=g.tj(v,g.vK(x,"emb_rel_end")),p.Ma("url",v)),(r=(r=r.sessionData)&&r.itct)&&p.api.fk(p.element,r));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.gi(e.element),g.Af(e);this.stills.length=c}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Ol())};
g.h.ES=function(){this.B+=this.stills.length;this.Ol()};
g.h.GS=function(){this.B-=this.stills.length;this.Ol()};
g.h.iN=function(){return this.j.Qh()};
g.h.pD=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.hn(),this.ub&&this.Ol()):(this.D=!0,this.ub&&A3(this)&&(2===a?this.j.Hu():3===a&&this.j.Sq()))};
g.h.DS=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.bb(this.stills[a].element,!0);this.pD(1)}else this.C=null,this.D=!1;this.Ol()};
g.h.Ae=function(){return this.ub&&A3(this)};g.w(C3,g.vL);g.h=C3.prototype;g.h.qr=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!QWa(this.player)||b;var c=a.ke||g.LC(a.B),d=this.player.xw();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Ae=function(){return this.endScreen.Ae()};
g.h.sV=function(){return this.Ae()?this.endScreen.iN():!1};
g.h.ra=function(){this.player.kf("endscreen");g.vL.prototype.ra.call(this)};
g.h.load=function(){var a=this.player.getVideoData();var b=a.LN;if(b&&b.videoId){var c=this.player.tb().Md.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.BK?a=!1:(this.player.qk(b.videoId,void 0,void 0,!0,!0,b),c&&c.VA("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.vL.prototype.load.call(this),this.endScreen.show())};
g.h.unload=function(){g.vL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.onCueRangeEnter=function(a){this.qr()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.onVideoDataChange=function(){SWa(this);this.B&&RWa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new v3(this.player):this.endScreen=new z3(this.player),g.H(this,this.endScreen),g.iL(this.player,this.endScreen.element,4))};g.uL("endscreen",C3);})(_yt_player);
